# Generated by Django 2.2.10 on 2020-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_postt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postt',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
