# Generated by Django 2.2.10 on 2020-08-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_postt_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postt',
            old_name='title',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='postt',
            old_name='desc',
            new_name='result',
        ),
    ]
